spring.application.name=proyectIoT

#BBDD
spring.datasource.url=jdbc:mariadb://localhost:3309/iot
#Para Podman en Linux, se ven los contenedores en la misma red
#spring.datasource.url=jdbc:mariadb://mariadb:3306/iot

spring.datasource.username=usuario
spring.datasource.password=usuario1234
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
# Activar log de DDL para ver el ALTER TABLE al arrancar
#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.tool.schema=DEBUG
#none - create
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect

#CORS
cors.allowed-origins=http://localhost:5173,http://localhost:3000,http://3.209.189.183:5173,http://3.209.189.183:3000

#MQTT
#mqtt.host=localhost
#mqtt.port=1883
mqtt.host=10.0.0.11
mqtt.port=1883

#MQTT LORA (suscripción a topic único)
mqtt.lora.enabled=true
mqtt.lora.host=eu1.cloud.thethings.network
mqtt.lora.port=8883
mqtt.lora.tls-enabled=true
mqtt.lora.username=pi2526-sector4-01@ttn
mqtt.lora.password=NNSXS.SLXZA7F26LYHF6HZCN7XNHCWLGT5ABA2SODSZDQ.RW6K6WQNEDFGXCPFI7XDGMG2J4HHXXNRG66GIC7RDW4DATB535VQ
mqtt.lora.topic=v3/pi2526-sector4-01@ttn/devices/esp32-rfm95-sector4/up

#NIVEL DE LOGGING
logging.level.root=INFO
logging.level.com.jaroso.proyectiot=INFO
logging.level.com.jaroso.proyectiot.services.SensorIngestionService=INFO
logging.level.com.jaroso.proyectiot.services.LoraMqttSubscriberService=INFO
logging.level.com.jaroso.proyectiot.services.MqttPublisher=INFO

